### ISSUE TITLE
Will there be support for the Xbox GHLive devices?

### ISSUE THREAD

**Issue by HastagGuigui** [evilynux/hid-ghlive-dkms#6]
I sincerely don't know if it's the right place to ask this, sorry if it's not

**Comment by msrodrigobr** [comment]
I have exactly the same question :D

**Comment by evilynux** [comment]
Sorry, I had not seen this issue before. Both the xbox360 and xboxone dongles "speak" a different language (not HID).

Support for the xboxone dongle has been added to the out-of-tree xpad DKMS that can be found there:
[https://github.com/paroj/xpad](https://github.com/paroj/xpad)

Evetually we should submit patches for direct inclusion into the kernel, but we haven't gotten around to it yet.

I don't own a xbox360 dongle, but it is my understanding that it is already supported by the xpad module (both upstream in-kernel and out-of-tree DKMS).
