### ISSUE TITLE
Can't Install on SteamOS 3.5

### ISSUE THREAD

**Issue by Ponjen** [evilynux/hid-ghlive-dkms#9]
Been using this string of commands (as root) for months now every OS update with no issues:

sudo steamos-readonly disable && sudo pacman -Syy && sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --populate && sudo pacman -S dkms && sudo pacman -S dkms linux-neptune-headers && sudo ./install.sh

Simple reboot, and Wii U Live guitar works with no issues. As of SteamOS 3.5, the driver cannot be installed (and is not in the new kernel by default). The error shows SteamOS 3.5 uses different headers for the new kernel, but the old command only gets the old kernel's headers. The headers needed are linux-headers-6.1.52-valve9-1-neptune-61, but what's downloaded is linux-headers-5.13.0-valve37-1-neptune. Using sudo pacman -S linux-headers doesn't work either. Not sure if there's a command to specify the new headers.

**Comment by Ponjen** [comment]
Found it. It's linux-neptune-61-headers.

**Comment by evilynux** [comment]
I'm glad you found a solution. I would expect `linux-neptune-headers` to point to the latest and greatest headers. Did you manually install a recent kernel or is it the one `linux-nepture-image` points to?

**Comment by Ponjen** [comment]
Never made any changes to the kernel, as far as I know.

**Comment by evilynux** [comment]
Nothing to be fixed, it was a matter of installing the right headers.
